arenaSignUpdater:
  delay: 20
titles:
  durationSeconds: 5
  fadeInTicks: 10
  fadeOutTicks: 10
prefix: '&4[&6&l1vs1&4]&r '
duelInvitationTimeOut: 60
checkForUpdates: true
database:
  type: 'sqlite'
  host: 'localhost'
  port: '3306'
  user: 'dbuser'
  password: 'dbpassword'
  database: 'database-name'